### ISSUE TITLE
FileBuilder test seems bad...

### ISSUE THREAD

**Issue by stretch1414** [IlluminusLimited/ImageService#5]
Needs rewritten...  Feels completely wrong.  Do I know how to write unit tests?  Probably not...

**Comment by scytherswings** [comment]
yeah, terrible. You should feel terrible. just terrible.

**Comment by stretch1414** [comment]
I thought it was clunky, but I guess not really an issue

**Comment by scytherswings** [comment]
We should probably revisit the tests for this project, mine aren't the best.. lol

**Comment by stretch1414** [comment]
Yeah maybe
